parser: "@typescript-eslint/parser"

env:
  node: true

parserOptions:
  ecmaVersion: 2021
  project: tsconfig.json
  sourceType: module

plugins:
  - simple-import-sort

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:prettier/recommended

rules:
  simple-import-sort/imports: "error"
  simple-import-sort/exports: "error"
  sort-imports: "off"
  react/react-in-jsx-scope: "off"
  "@typescript-eslint/no-namespace": "off"

settings:
  react:
    version: detect

ignorePatterns:
  - /src/graphql/types.ts
  - next.config.js
